Fix pahole flags
starfive-tech/beagle_kernel_5.10 pull request #87
Opened 2023-03-10 15:47 UTC by saeziae

This patch fixes build on host with higher version of pahole.

2023-03-11 13:00 UTC, JamiKettunen requested changes
So basically this is just a cherry-pick of https://github.com/torvalds/linux/commit/9741e07ece7c? Why not make it as such instead of hand-crafting whatever this is without original commit authorship etc?

Add [torvalds' repository](https://github.com/torvalds/linux) as a remote in your local clone of this one, fetch it and `git cherry-pick -x` the commit by hash, fixing conflicts if any arise and test that is still works as expected, thank you ^^

2023-03-11 13:00 UTC, JamiKettunen commented on scripts/link-vmlinux.sh
> +		if is_enabled CONFIG_CPU_UNRET_ENTRY; then
This will never be run on a v5.15 kernel source which is what you're making this PR against, [`CONFIG_CPU_UNRET_ENTRY` was added in v5.19](https://cateee.net/lkddb/web-lkddb/CPU_UNRET_ENTRY.html), drop this

2023-03-11 13:00 UTC, JamiKettunen commented on scripts/link-vmlinux.sh
> +		if [ -n "${CONFIG_SLS}" ]; then
Ditto, [`CONFIG_SLS` was added in v5.17](https://cateee.net/lkddb/web-lkddb/SLS.html), drop this

2023-03-11 18:43 UTC, saeziae commented
yes i found cherry pick upstream is a bit different from what is needed, so i dumped part of 5.15.98 patch from kernel.org, which does not contain authorship. thank you for telling me the 5.15 maintenance repo, i will re commit this patch.

2023-03-18 20:03 UTC, saeziae commented
Picked upstream commits.
Tested.

2023-11-03 14:04 UTC, closed without merging